services:
  app:
    container_name: django_start
    build: .
    volumes:
      - ./:/django_start
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    command: sh -c "python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
  db:
    image: postgres:15
    container_name: postgres_django_db
    restart: always
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "django"
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    container_name: redis-django-app
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
volumes:
  postgres_data:
  redis_data:
