# Generated by Django 5.2.11 on 2026-02-27 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('genre', models.CharField(blank=True, choices=[('1', 'rpg'), ('2', 'shooter'), ('3', 'strategy')], max_length=64)),
                ('description', models.TextField(blank=True, max_length=200)),
                ('wikipedia', models.URLField(blank=True, default='https://wikipedia.com')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, unique=True)),
                ('email', models.EmailField(max_length=64, unique=True)),
                ('photo', models.ImageField(blank=True, help_text='Please put in your photo', upload_to='')),
                ('age', models.IntegerField(blank=True)),
                ('birthday', models.DateField(blank=True)),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
