# Generated by Django 6.0.2 on 2026-10-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_db", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Please put in your photo",
                upload_to="",
                verbose_name="photo",
            ),
        ),
    ]
