# Generated by Django 5.2.11 on 2026-02-28 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_db', '0004_alter_client_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='wikipedia',
            new_name='wiki_page',
        ),
    ]
