# Generated by Django 5.2.11 on 2026-03-04 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_db', '0005_rename_wikipedia_game_wiki_page'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=models.CharField(blank=True, choices=[('1', 'rpg'), ('2', 'shooter'), ('3', 'strategy')], help_text='Please select genre of game', max_length=64),
        ),
        migrations.CreateModel(
            name='GameList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_list', models.ManyToManyField(to='django_db.game', verbose_name='Games for PC')),
                ('gamer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
