# Generated by Django 5.2.11 on 2026-03-04 15:36

import phone_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_db', '0007_alter_gamelist_gamer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='email',
        ),
        migrations.RemoveField(
            model_name='client',
            name='username',
        ),
        migrations.AddField(
            model_name='client',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Please enter your phone number', max_length=31),
        ),
    ]
