# Generated by Django 5.2.11 on 2026-03-04 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_db', '0008_remove_client_email_remove_client_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='client',
            name='username',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
    ]
